name: Putra's GHP
url: http://mputrap.github.io
description: A page full of absurdities

permalink: /:year/:month/:day/:title/
paginate: 10

gems: [jekyll-paginate]
exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
